//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1920_xyy.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_1920_xyy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept.
        /// </summary>
        public static string AcceptAnswearView_Accept {
            get {
                return ResourceManager.GetString("AcceptAnswearView_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string AcceptAnswearView_Back {
            get {
                return ResourceManager.GetString("AcceptAnswearView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do u want to accept this answer ?.
        /// </summary>
        public static string AcceptAnswearView_MSG {
            get {
                return ResourceManager.GetString("AcceptAnswearView_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string AcceptAnswearView_Remove {
            get {
                return ResourceManager.GetString("AcceptAnswearView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string AddCommentView_Add {
            get {
                return ResourceManager.GetString("AddCommentView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a comment (￣▽￣)ノ.
        /// </summary>
        public static string AddCommentView_AddComment {
            get {
                return ResourceManager.GetString("AddCommentView_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string AddCommentView_Cancel {
            get {
                return ResourceManager.GetString("AddCommentView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add 3 tags max.
        /// </summary>
        public static string AskView_Addtag {
            get {
                return ResourceManager.GetString("AskView_Addtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ask.
        /// </summary>
        public static string AskView_Ask {
            get {
                return ResourceManager.GetString("AskView_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body.
        /// </summary>
        public static string AskView_Body {
            get {
                return ResourceManager.GetString("AskView_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string AskView_Title {
            get {
                return ResourceManager.GetString("AskView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ask your question :).
        /// </summary>
        public static string AskView_TitlePage {
            get {
                return ResourceManager.GetString("AskView_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string DeleteView_Cancel {
            get {
                return ResourceManager.GetString("DeleteView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are u sure u want to delete this post ? .
        /// </summary>
        public static string DeleteView_DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteView_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string DeleteView_Yes {
            get {
                return ResourceManager.GetString("DeleteView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string EditCommmentView_Back {
            get {
                return ResourceManager.GetString("EditCommmentView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string EditCommmentView_Delete {
            get {
                return ResourceManager.GetString("EditCommmentView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string EditCommmentView_Save {
            get {
                return ResourceManager.GetString("EditCommmentView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit your comment (◑‿◐).
        /// </summary>
        public static string EditCommmentView_Title {
            get {
                return ResourceManager.GetString("EditCommmentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All tags.
        /// </summary>
        public static string EditPostView_AllTags {
            get {
                return ResourceManager.GetString("EditPostView_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string EditPostView_Edit {
            get {
                return ResourceManager.GetString("EditPostView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your post tags.
        /// </summary>
        public static string EditPostView_PostTags {
            get {
                return ResourceManager.GetString("EditPostView_PostTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit your post.
        /// </summary>
        public static string EditPostView_Title {
            get {
                return ResourceManager.GetString("EditPostView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This tag already exist.
        /// </summary>
        public static string Error_AlreadyExist {
            get {
                return ResourceManager.GetString("Error_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 8.
        /// </summary>
        public static string Error_LengthGreaterEqual8 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password needs to contains a Maj, a number and a special char.
        /// </summary>
        public static string Error_Password_Format {
            get {
                return ResourceManager.GetString("Error_Password_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords don&apos;t match ech other.
        /// </summary>
        public static string Error_PasswordMisMatch {
            get {
                return ResourceManager.GetString("Error_PasswordMisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot follow this member because he has the maximum of followers.
        /// </summary>
        public static string Error_TooMuchFollowers {
            get {
                return ResourceManager.GetString("Error_TooMuchFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UserName already taken, pls chose another one.
        /// </summary>
        public static string Error_UserNameTaken {
            get {
                return ResourceManager.GetString("Error_UserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email must be valid.
        /// </summary>
        public static string Error_WrongMailFormat {
            get {
                return ResourceManager.GetString("Error_WrongMailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string IndexTabName {
            get {
                return ResourceManager.GetString("IndexTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string IndexView_Active {
            get {
                return ResourceManager.GetString("IndexView_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à asked by.
        /// </summary>
        public static string IndexView_AskedBy {
            get {
                return ResourceManager.GetString("IndexView_AskedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string IndexView_Delete {
            get {
                return ResourceManager.GetString("IndexView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dislike.
        /// </summary>
        public static string IndexView_Dislike {
            get {
                return ResourceManager.GetString("IndexView_Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Like.
        /// </summary>
        public static string IndexView_Like {
            get {
                return ResourceManager.GetString("IndexView_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Looking for.
        /// </summary>
        public static string IndexView_Look {
            get {
                return ResourceManager.GetString("IndexView_Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb of answears : .
        /// </summary>
        public static string IndexView_NbAnswears {
            get {
                return ResourceManager.GetString("IndexView_NbAnswears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newest.
        /// </summary>
        public static string IndexView_Newest {
            get {
                return ResourceManager.GetString("IndexView_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort by.
        /// </summary>
        public static string IndexView_Sort {
            get {
                return ResourceManager.GetString("IndexView_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We &lt;3 stuck peoples.
        /// </summary>
        public static string IndexView_Title {
            get {
                return ResourceManager.GetString("IndexView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unansweared.
        /// </summary>
        public static string IndexView_Unansweared {
            get {
                return ResourceManager.GetString("IndexView_Unansweared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote.
        /// </summary>
        public static string IndexView_Vote {
            get {
                return ResourceManager.GetString("IndexView_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If your don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo.
        /// </summary>
        public static string LoginView_Pseudo {
            get {
                return ResourceManager.GetString("LoginView_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Members.
        /// </summary>
        public static string MembersTabName {
            get {
                return ResourceManager.GetString("MembersTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ask a question.
        /// </summary>
        public static string Menu_AskQuestion {
            get {
                return ResourceManager.GetString("Menu_AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TagList.
        /// </summary>
        public static string Menu_TagList {
            get {
                return ResourceManager.GetString("Menu_TagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Answears.
        /// </summary>
        public static string QuestionView_Answears {
            get {
                return ResourceManager.GetString("QuestionView_Answears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à by.
        /// </summary>
        public static string QuestionView_By {
            get {
                return ResourceManager.GetString("QuestionView_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string QuestionView_Comment {
            get {
                return ResourceManager.GetString("QuestionView_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post.
        /// </summary>
        public static string QuestionView_Post {
            get {
                return ResourceManager.GetString("QuestionView_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Answear this question.
        /// </summary>
        public static string QuestionView_Rep {
            get {
                return ResourceManager.GetString("QuestionView_Rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tshe.
        /// </summary>
        public static string QuestionView_The {
            get {
                return ResourceManager.GetString("QuestionView_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote.
        /// </summary>
        public static string QuestionView_Vote {
            get {
                return ResourceManager.GetString("QuestionView_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string SignUpView_Cancel {
            get {
                return ResourceManager.GetString("SignUpView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HERE.
        /// </summary>
        public static string SignUpView_ClickHere {
            get {
                return ResourceManager.GetString("SignUpView_ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comfirm.
        /// </summary>
        public static string SignUpView_Comfirm {
            get {
                return ResourceManager.GetString("SignUpView_Comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string SignUpView_Email {
            get {
                return ResourceManager.GetString("SignUpView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FullName.
        /// </summary>
        public static string SignUpView_FullName {
            get {
                return ResourceManager.GetString("SignUpView_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have an acount ? click .
        /// </summary>
        public static string SignUpView_Message {
            get {
                return ResourceManager.GetString("SignUpView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SignUpView_Password {
            get {
                return ResourceManager.GetString("SignUpView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comfirm password.
        /// </summary>
        public static string SignUpView_PasswordComfirm {
            get {
                return ResourceManager.GetString("SignUpView_PasswordComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signup.
        /// </summary>
        public static string SignUpView_Title {
            get {
                return ResourceManager.GetString("SignUpView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UserName.
        /// </summary>
        public static string SignUpView_UserName {
            get {
                return ResourceManager.GetString("SignUpView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a tag.
        /// </summary>
        public static string TagsView_AddTag {
            get {
                return ResourceManager.GetString("TagsView_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string TagsView_Delete {
            get {
                return ResourceManager.GetString("TagsView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit the tag .
        /// </summary>
        public static string TagsView_EditTag {
            get {
                return ResourceManager.GetString("TagsView_EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gooo.
        /// </summary>
        public static string TagsView_Go {
            get {
                return ResourceManager.GetString("TagsView_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à posts.
        /// </summary>
        public static string TagsView_Post {
            get {
                return ResourceManager.GetString("TagsView_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tags List.
        /// </summary>
        public static string TagsView_Title {
            get {
                return ResourceManager.GetString("TagsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string VoteView_Back {
            get {
                return ResourceManager.GetString("VoteView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👎.
        /// </summary>
        public static string VoteView_Dislike {
            get {
                return ResourceManager.GetString("VoteView_Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👍.
        /// </summary>
        public static string VoteView_Like {
            get {
                return ResourceManager.GetString("VoteView_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote for this post ☜(˚▽˚)☞.
        /// </summary>
        public static string VoteView_Title {
            get {
                return ResourceManager.GetString("VoteView_Title", resourceCulture);
            }
        }
    }
}
